version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: TASK_DEF_ARN
        LoadBalancerInfo:
          ContainerName: webserver-staging
          ContainerPort: 80

